# Generated by Django 4.2 on 2023-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(max_length=50)),
                ('co2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=50)),
                ('co2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MotorBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeType', models.CharField(max_length=50)),
                ('co2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicTransitType', models.CharField(max_length=50)),
                ('co2', models.FloatField()),
            ],
        ),
    ]
