# Generated by Django 4.2 on 2023-04-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carType',
            new_name='car_type',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flightType',
            new_name='flight_type',
        ),
        migrations.RenameField(
            model_name='motorbike',
            old_name='bikeType',
            new_name='bike_type',
        ),
        migrations.RenameField(
            model_name='publictransit',
            old_name='publicTransitType',
            new_name='public_transit_type',
        ),
    ]
